---
- name: Getting list of console commands
  shell: "php /vagrant/bin/console list"
  register: commands_list

- name: Setting fact of DoctrineFixturesBundle presence.
  set_fact:
    doctrine_fixtures_bundle_is_present: '"doctrine:fixtures:load" in commands_list'

- debug:
    msg: 'Doctrine fixtures bundle is not present. Skipping fixtures appending.'
  when: doctrine_fixtures_bundle_is_present != true

- name: Appending doctrine fixtures
  shell: "php /vagrant/bin/console doctrine:fixtures:load --append"
  args:
    chdir: /vagrant
  when: doctrine_fixtures_bundle_is_present == true