---
apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"
apache_remove_default_vhost: true
apache_mods_enabled:
  - rewrite.load
apache_state: started

apache_vhosts:
  # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
  - servername: "symfony.local"
    extra_parameters: |
      DocumentRoot "/vagrant/web"
      <Directory "/vagrant/web">
          AllowOverride None
          Require all granted

          <IfModule mod_rewrite.c>
              Options -MultiViews
              RewriteEngine On
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteRule ^(.*)$ app.php [QSA,L]
          </IfModule>
      </Directory>

      # uncomment the following lines if you install assets as symlinks
      # or run into problems when compiling LESS/Sass/CoffeeScript assets
      <Directory /vagrant>
          Options FollowSymlinks
      </Directory>

      # optionally disable the RewriteEngine for the asset directories
      # which will allow apache to simply reply with a 404 when files are
      # not found instead of passing the request into the full symfony stack
      <Directory /vagrant/web/bundles>
          <IfModule mod_rewrite.c>
              RewriteEngine Off
          </IfModule>
      </Directory>
      ErrorLog /var/log/apache2/project_error.log
      CustomLog /var/log/apache2/project_access.log combined