---
env:
 RUNLEVEL: 1
php_version: "7.1"
php_enable_apc: true
php_enable_webserver: true
php_enable_php_fpm: true
php_webserver_daemon: "nginx"

# Vendor-specific configuration paths on Debian/Ubuntu make my brain asplode.
php_conf_paths:
  - "/etc/php/{{ php_version }}/fpm"
  - "/etc/php/{{ php_version }}/apache2"
  - "/etc/php/{{ php_version }}/cli"

php_extension_conf_paths:
  - "/etc/php/{{ php_version }}/fpm/conf.d"
  - "/etc/php/{{ php_version }}/apache2/conf.d"
  - "/etc/php/{{ php_version }}/cli/conf.d"

php_apc_conf_filename: 20-apcu.ini
php_opcache_conf_filename: 05-opcache.ini
php_fpm_daemon: "php{{ php_version }}-fpm"
php_fpm_conf_path: "/etc/php/{{ php_version }}/fpm"
php_fpm_pool_conf_path: "{{ php_fpm_conf_path }}/pool.d/www.conf"

php_fpm_pool_user: ubuntu
php_fpm_pool_group: ubuntu

php_packages:
    - "libpcre3-dev"
    - "php-apcu"
    - "php-date"
    - "php{{ php_version }}-common"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-dev"
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-bcmath"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-intl"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-opcache"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-mcrypt"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-zip"
